Apple_HomePage_Clone
Takhmina175/Apple_HomePageClone pull request #1
Opened 2020-09-05 20:08 UTC by Takhmina175

2020-09-09 20:39 UTC, Takhmina175 commented
The Apple webpage clone consists of a header, main, and footer sections.
I used HTML and CSS technologies for building a Web page.
To create a web page, I used the following elements:
•	Grids and flex to layout elements on the page
•	Element positioning  to move elements from one position to another
•	Embedding images 
•	Using images as a background 
•	Adding gradients to the element

2020-09-09 21:15 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find the comments below**
##

**REQUIRED CHANGES**

- [ ] The CSS background should `cover` the whole page irrespective of the screen size. This will be a learning opportunity for the students to use background-size and position properties. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/building_with_backgrounds_and_gradients/background_size_requirement.png) from [pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59538830/))

![image](https://user-images.githubusercontent.com/60184961/92654713-ea018200-f2f8-11ea-9afd-f371bea83a59.png)

So please apply the proper CSS rules to make your background image cover the whole width.

- [ ] The bottom section shouldn't be left-aligned. Please apply the proper CSS rules to fix it.

![image](https://user-images.githubusercontent.com/60184961/92655073-81ff6b80-f2f9-11ea-910b-93357d0b0e53.png)

- [ ] Navbar items should be aligned center. Please apply the proper CSS rules to make the navbar items aligned center.

![image](https://user-images.githubusercontent.com/60184961/92655203-b5da9100-f2f9-11ea-9be8-da72f4a916a8.png)

- [ ] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright)

So please apply DRY CSS to prevent repeating the same CSS rules in your stylesheet.

- [ ] The other required changes are listed below, please check and fix them.

##

**OPTIONAL CHANGES**

- [ ] You can use a code-formatter to prevent redundant spaces and empty lines in your codes.

- [ ] Consider the use of the [`<main>` tag](https://www.w3schools.com/tags/tag_main.asp) for the dominant content of the `<body>` of a document

##

**NOTES**

Please use the imperative tense for your commit messages instead of the present tense in your upcoming projects.
##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready*

Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/)

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-09-09 21:15 UTC, SafaErden commented on README.md
> +Feel free to check the [issues page](issues/).
- [ ] This link is broken please kindly fix it.

2020-09-09 21:15 UTC, SafaErden commented on README.md
> +This project is [MIT](lic.url) licensed.
- [ ] This link is also broken, please fix this too.

2020-09-09 21:15 UTC, SafaErden commented on README.md
> +- etc
- [ ] As far as I understand, this section is forgotten to be updated. It contains sentences from the default README template. If you do not need this section please remove it.

2020-09-09 21:15 UTC, SafaErden commented on index.html
> +</div>
- [ ] The bottom contains four elements which are links (to other articles or #). So please apply the proper HTML tags to these items to make them links.

2020-09-12 19:21 UTC, moinkhanif requested changes
##  Status: Changes Required ⚠️ 

Hey @Takhmina175 , Thank you for doing the mandatory and optional changes requested by the previous reviewer. Your project looks great. ✨

However, there are **3 mandatory changes** requested based on the previous review, and a **few optional** ones. Kindly fix the issues requested in the comments below.

**Note**: The project shall be approved on the completion of mandatory changes. However, it would be great if you also looked into the optional ones so your project is more professional. 😄

If you have any issues, feel free to reach out to me on slack or any other medium.

My username on slack/twitter/GitHub: **@MoinKhanIF**

Happy coding! 🐱‍🏍

2020-09-12 19:21 UTC, moinkhanif commented on README.md
> +Additional description about the project and its features.
- [ ] **It contains sentences from the default README template.** Please add information **related** to the project.

2020-09-12 19:21 UTC, moinkhanif commented on index.html
> +              </a>
**[OPTIONAL]**  Enclosing other links within an `a` tag does not allow the user to click on nested links. Therefore, kindly refrain from nesting other links within the `a` tag.

In this case, I'd suggest you to replace the `a` tag with `div` and the `div` tags with `a`.(Kindly note that this might change the color of the nav links, so you'll have to style it accordingly).

Example: 
```
<div class="link1 d-flex align-center f-weight textColor">
	<a href="#" class="box"<h2>Store</h2></a>
```

2020-09-12 19:21 UTC, moinkhanif commented on index.html
> +  </a>
**[OPTIONAL]**  Enclosing other links within an `a` tag does not allow the user to click on nested links. Therefore, kindly refrain from nesting other links within the `a` tag.

In this case, I'd suggest you to replace the `a` tag with `div` and the `span` tags(accordingly) with `a`.

2020-09-12 19:21 UTC, moinkhanif commented on index.html
> +        </div>
- [ ] This section seems left aligned on larger screens as pointed out by the previous reviewer. Kindly fix it so the section matches the width of the header(in this case, full width).

	**Hint**: You could give full width to `.wrapping_imgs`, `.item` and `.phone`.

- [ ] Kindly use `a` tags instead of `div` in the tag where the class is `'item'` as they are supposed to be links.

![Screenshot 2020-09-13 000900](https://user-images.githubusercontent.com/6555800/93002553-6db7aa80-f555-11ea-9ff1-57f6faf3f2db.png)

2020-09-12 22:30 UTC, moinkhanif approved these changes
##  Status: Approved! 🥳  

Hey @Takhmina175, great work completing both mandatory and optional requests from the previous review! 🎉 It's nice that you reused styles to the sections discussed above and solved it. Your project has been approved.

You may now merge the branch. Wishing you the best with your future projects.

Happy coding! 🐱‍🏍

2020-09-12 22:38 UTC, merged